name: spinor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.1
  - ffmpeg
  - scikit-image
  - tqdm
  - matplotlib
  - numpy
